version: '3'

services:
  db:
    image: postgres:10.2
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=nepalinewsserver
      - POSTGRES_PASSWORD=p@ssw0rd
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pg_data: {}
  pg_backups: {}
